implement rm,commit,usage method
-fixed add method to work with an absolut path
-fixed script and working directory path
-added rm, commit and usage method

diff --git a/cfgkeeper b/cfgkeeper
--- a/cfgkeeper
+++ b/cfgkeeper
@@ -1,80 +1,82 @@
 #!/usr/bin/env bash
-# vim: ft=bash:tabstop=4
+# vim: ft=bash ts=4
 
-SD=`pwd`
+WD=`pwd`
+SD=`dirname $0`
 
 . ~/.config/cfgkeeperrc
 
-cvs=`basename ${VCS}`
-. ${SD}/cfgkeeper.${cvs##.*}
-
+vcs=`basename $VCS`
+. $SD/cfgkeeper.${vcs##.*}	
 
 _add(){
-	if [ -f "${1}" ]; then
-		# TODO get abolut path without ..
-		local DSTD=${BAKDIR}$(dirname "${1}")
-		mkdir -p "${DSTD}"
-		DSTD=${DSTD}/$(basename "${1}")
-		cp -dp "${1}" "${DSTD}"
-		vcs_add "${1#/}"
-		local RET=$?
-		[ 0 = ${RET} ] && echo "add: ${1}" && return 0
-	elif [ -d "${1}" ]; then
-		echo "add error: add files separately."
-		return 1
+	local fp=$1
+	if [ ! "${fp:0:1}" = "/" ]; then
+		fp=$(cd $(dirname "$WD/$fp"); pwd -P)/$(basename "$fp")
 	fi
 
-	echo "add error: ${RET}"
+	if [ -f "$fp" ]; then
+		local dp="$BAKDIR`dirname "$fp"`"
+		mkdir -p "$dp"
+		dp=$dp/`basename "${1}"`
+		cp -dp "$fp" "$dp"
+		vcs_add "${fp#/}"
+		[ $? = 0 ] && echo "add $fp"
+	elif [ -d "$1" ]; then
+		echo "error: add files separately."
+	fi
 
-	return 1
+	return 0
 }
 
-_del(){
-	echo "del"
+_rm(){
+	local fp=$1
+	if [ ! "${fp:0:1}" = "/" ]; then
+		fp=$(cd $(dirname "$WD/$fp"); pwd -P)/$(basename "$fp")
+	fi
+
+	if [ -f "${BAKDIR}${fp}" ]; then
+		vcs_rm "${fp#/}"
+	elif [ -d "${BAKDIR}${fp}" ]; then
+		echo "error: remove files separatley."
+	fi
+	
+	return 0
 }
 
 _commit(){
 	vcs_commit "${1}"
-	local RET=$?
-	[ 0 = ${RET} ] && echo "set commited." && return 0
-	echo "commit error: ${RET}"
+	[ 0 = $? ] && echo "set commited." 
 }
-
 
 _usage(){
-	echo "use: $0 (add|del) object"
+	echo -en "usage: $(basename $0)\n"
+	echo -en "   add FILE\tAdd a file to the commit set\n"
+	echo -en "   rm FILE\tRemove a file from the backup\n"
+	echo -en "   commit MSG\tRecord changes to the repository\n"
+	echo -en "   status\tShow the repositors status\n"
+	echo -en "   check\tShow tracked file changes\n"
+	echo -en "   *\t\tForward arguments to $vcs\n"
+	echo -en "\n"
 }
 
+_check(){
+	echo "TODO check"
+}
+
+[ $# = 0 ] && _usage && exit
 
 case "$1" in
-	add)
-		[ $# = 2 ] && _add "${SD}/$2"
-		[ $? = 1 ] && _usage
-  		;;
+	add)	[ $# = 2 ] && _add "$2" || _usage;;
 
-	del)
-		[ $# = 2 ] && _del "${SD}/$2"
-		[ $? = 1 ] && _usage
-		;;
+	rm)		[ $# = 2 ] && _rm "$2" || _usage;;
 
-	co) 
-		[ $# = 2 ] && _commit "$2"
-		[ $? = 1 ] && _usage
-		;;
+	commit)	[ $# = 2 ] && _commit "$2" || _usage;;
 
-	push) ;;
+	status)	vcs_status;;
 
-	pull) ;;
+	check)	_check;;
 
-	status) vcs_status;;
-
-	pt) shift; vcs_pt $@;;
-
-
-
-	*) _usage;;
+	*)		vcs_pt $@;;
 esac
-
-# list set
-# list path 
 
